//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace aerosoltasktoday.Models.Data_context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class aerosoltaskEntities : DbContext
    {
        public aerosoltaskEntities()
            : base("name=aerosoltaskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aerosol_table> aerosol_table { get; set; }
    
        public virtual ObjectResult<sp_aerosol_Result> sp_aerosol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_aerosol_Result>("sp_aerosol");
        }
    }
}
